using SpaceTradersWPF.Types;

namespace SpaceTradersWPF.Extensions;

internal static class FactionTraitsExtensions
{
    public static string ToApiString(this FactionTraits waypointTypes)
    {
        return waypointTypes switch
        {
            FactionTraits.Bureaucratic => "BUREAUCRATIC",
            FactionTraits.Secretive => "SECRETIVE",
            FactionTraits.Capitalistic => "CAPITALISTIC",
            FactionTraits.Industrious => "INDUSTRIOUS",
            FactionTraits.Peaceful => "PEACEFUL",
            FactionTraits.Distrustful => "DISTRUSTFUL",
            FactionTraits.Welcoming => "WELCOMING",
            FactionTraits.Anarchist => "ANARCHIST",
            FactionTraits.Conflicted => "CONFLICTED",
            FactionTraits.Authoritarian => "AUTHORITARIAN",
            FactionTraits.Oligarchical => "OLIGARCHICAL",
            FactionTraits.Dynastic => "DYNASTIC",
            FactionTraits.Democratic => "DEMOCRATIC",
            FactionTraits.Decentralized => "DECENTRALIZED",
            FactionTraits.Smugglers => "SMUGGLERS",
            FactionTraits.Scavengers => "SCAVENGERS",
            FactionTraits.Rebellious => "REBELLIOUS",
            FactionTraits.Exiles => "EXILES",
            FactionTraits.Pirates => "PIRATES",
            FactionTraits.Raiders => "RAIDERS",
            FactionTraits.Clan => "CLAN",
            FactionTraits.Guild => "GUILD",
            FactionTraits.Dominion => "DOMINION",
            FactionTraits.Fringe => "FRINGE",
            FactionTraits.Forsaken => "FORSAKEN",
            FactionTraits.Isolated => "ISOLATED",
            FactionTraits.Localized => "LOCALIZED",
            FactionTraits.Established => "ESTABLISHED",
            FactionTraits.Notable => "NOTABLE",
            FactionTraits.Dominant => "DOMINANT",
            FactionTraits.Inescapable => "INESCAPABLE",
            FactionTraits.Innovative => "INNOVATIVE",
            FactionTraits.Bold => "BOLD",
            FactionTraits.Visionary => "VISIONARY",
            FactionTraits.Curious => "CURIOUS",
            FactionTraits.Daring => "DARING",
            FactionTraits.Exploratory => "EXPLORATORY",
            FactionTraits.Resourceful => "RESOURCEFUL",
            FactionTraits.Flexible => "FLEXIBLE",
            FactionTraits.Cooperative => "COOPERATIVE",
            FactionTraits.United => "UNITED",
            FactionTraits.Strategic => "STRATEGIC",
            FactionTraits.Intelligent => "INTELLIGENT",
            FactionTraits.ResearchFocused => "RESEARCH_FOCUSED",
            FactionTraits.Collaborative => "COLLABORATIVE",
            FactionTraits.Progressive => "PROGRESSIVE",
            FactionTraits.Militaristic => "MILITARISTIC",
            FactionTraits.TechnologicallyAdvanced => "TECHNOLOGICALLY_ADVANCED",
            FactionTraits.Aggresive => "AGGRESIVE",
            FactionTraits.Imperialistic => "IMPERIALISTIC",
            FactionTraits.TreasureHunter => "TREASURE_HUNTER",
            FactionTraits.Dexterous => "DEXTEROUS",
            FactionTraits.Unpredictable => "UNPREDICTABLE",
            FactionTraits.Brutal => "BRUTAL",
            FactionTraits.Fleeting => "FLEETING",
            FactionTraits.Adaptable => "ADAPTABLE",
            FactionTraits.SelfSufficient => "SELF_SUFFICIENT",
            FactionTraits.Defensive => "DEFENSIVE",
            FactionTraits.Proud => "PROUD",
            FactionTraits.Diverse => "DIVERSE",
            FactionTraits.Independent => "INDEPENDENT",
            FactionTraits.SelfInterested => "SELF_INTERESTED",
            FactionTraits.Fragmented => "FRAGMENTED",
            FactionTraits.Commercial => "COMMERCIAL",
            FactionTraits.FreeMarkets => "FREE_MARKETS",
            FactionTraits.Entrepreneurial => "ENTREPRENEURIAL",
            _ => "INVALID_FACTION_TRAIT"
        };
    }

    public static FactionTraits FromApiString(this string apiString)
    {
        return apiString switch
        {
            "BUREAUCRATIC" => FactionTraits.Bureaucratic,
            "SECRETIVE" => FactionTraits.Secretive,
            "CAPITALISTIC" => FactionTraits.Capitalistic,
            "INDUSTRIOUS" => FactionTraits.Industrious,
            "PEACEFUL" => FactionTraits.Peaceful,
            "DISTRUSTFUL" => FactionTraits.Distrustful,
            "WELCOMING" => FactionTraits.Welcoming,
            "ANARCHIST" => FactionTraits.Anarchist,
            "CONFLICTED" => FactionTraits.Conflicted,
            "AUTHORITARIAN" => FactionTraits.Authoritarian,
            "OLIGARCHICAL" => FactionTraits.Oligarchical,
            "DYNASTIC" => FactionTraits.Dynastic,
            "DEMOCRATIC" => FactionTraits.Democratic,
            "DECENTRALIZED" => FactionTraits.Decentralized,
            "SMUGGLERS" => FactionTraits.Smugglers,
            "SCAVENGERS" => FactionTraits.Scavengers,
            "REBELLIOUS" => FactionTraits.Rebellious,
            "EXILES" => FactionTraits.Exiles,
            "PIRATES" => FactionTraits.Pirates,
            "RAIDERS" => FactionTraits.Raiders,
            "CLAN" => FactionTraits.Clan,
            "GUILD" => FactionTraits.Guild,
            "DOMINION" => FactionTraits.Dominion,
            "FRINGE" => FactionTraits.Fringe,
            "FORSAKEN" => FactionTraits.Forsaken,
            "ISOLATED" => FactionTraits.Isolated,
            "LOCALIZED" => FactionTraits.Localized,
            "ESTABLISHED" => FactionTraits.Established,
            "NOTABLE" => FactionTraits.Notable,
            "DOMINANT" => FactionTraits.Dominant,
            "INESCAPABLE" => FactionTraits.Inescapable,
            "INNOVATIVE" => FactionTraits.Innovative,
            "BOLD" => FactionTraits.Bold,
            "VISIONARY" => FactionTraits.Visionary,
            "CURIOUS" => FactionTraits.Curious,
            "DARING" => FactionTraits.Daring,
            "EXPLORATORY" => FactionTraits.Exploratory,
            "RESOURCEFUL" => FactionTraits.Resourceful,
            "FLEXIBLE" => FactionTraits.Flexible,
            "COOPERATIVE" => FactionTraits.Cooperative,
            "UNITED" => FactionTraits.United,
            "STRATEGIC" => FactionTraits.Strategic,
            "INTELLIGENT" => FactionTraits.Intelligent,
            "RESEARCH_FOCUSED" => FactionTraits.ResearchFocused,
            "COLLABORATIVE" => FactionTraits.Collaborative,
            "PROGRESSIVE" => FactionTraits.Progressive,
            "MILITARISTIC" => FactionTraits.Militaristic,
            "TECHNOLOGICALLY_ADVANCED" => FactionTraits.TechnologicallyAdvanced,
            "AGGRESIVE" => FactionTraits.Aggresive,
            "IMPERIALISTIC" => FactionTraits.Imperialistic,
            "TREASURE_HUNTER" => FactionTraits.TreasureHunter,
            "DEXTEROUS" => FactionTraits.Dexterous,
            "UNPREDICTABLE" => FactionTraits.Unpredictable,
            "BRUTAL" => FactionTraits.Brutal,
            "FLEETING" => FactionTraits.Fleeting,
            "ADAPTABLE" => FactionTraits.Adaptable,
            "SELF_SUFFICIENT" => FactionTraits.SelfSufficient,
            "DEFENSIVE" => FactionTraits.Defensive,
            "PROUD" => FactionTraits.Proud,
            "DIVERSE" => FactionTraits.Diverse,
            "INDEPENDENT" => FactionTraits.Independent,
            "SELF_INTERESTED" => FactionTraits.SelfInterested,
            "FRAGMENTED" => FactionTraits.Fragmented,
            "COMMERCIAL" => FactionTraits.Commercial,
            "FREE_MARKETS" => FactionTraits.FreeMarkets,
            "ENTREPRENEURIAL" => FactionTraits.Entrepreneurial,
            _ => FactionTraits.NotDefined
        };
    }
}
